### ISSUE TITLE
Namespace \V[v]iew\ inconsistency

### ISSUE THREAD

**Issue by alex7r** [joomplace/X#41]
Check the functionality on linux system, it seems like small `v` should be used when creating "View Class name" in controllers to avoid inconsistency

**Comment by Dekabrist** [comment]
Confirmed.
Small v work on linux & windows platform
Big V only work on windows because for windows characters registry not necessary in directory name.

**Comment by alex7r** [comment]
Yes, and **we should stick to small 'v'**, as Joomla looks at 'views' when trying to find xml manifests for creating menu items.
